import type { ObservabilitySnapshot } from '@/modules/database-manager/domain/observability'

export function observabilityFixture(
  overrides: Partial<ObservabilitySnapshot> = {},
): ObservabilitySnapshot {
  return {
    activity: {
      data: {
        active: 3,
        blocked: 1,
        idle: 4,
        idleInTransaction: 1,
        longRunning: 2,
        waiting: 1,
      },
      status: 'available',
    },
    clusterIo: {
      evictions: '7',
      extends: '8',
      fsyncs: '9',
      hits: '1000',
      readOperationBytes: '4096',
      reads: '10',
      reuses: '11',
      statsResetAt: '2026-07-20T10:00:00.000Z',
      timing: {
        data: {
          extendTimeMs: 1,
          fsyncTimeMs: 2,
          readTimeMs: 3,
          writeTimeMs: 4,
          writebackTimeMs: 5,
        },
        status: 'available',
      },
      writeOperationBytes: '8192',
      writebacks: '12',
      writes: '13',
    },
    collectionLagHintMs: 500,
    connections: {
      configuredMaximum: 100,
      observed: 12,
      regularCapacity: 94,
      reserved: 3,
      superuserReserved: 3,
      utilizationPercent: 12,
    },
    currentDatabase: 'postgres',
    databases: [
      {
        activeTimeMs: 5000,
        blocksRead: '100',
        bufferCacheHitPercent: 99.5,
        bufferHits: '9999',
        checksumFailures: '0',
        checksumLastFailureAt: null,
        currentConnections: 4,
        database: 'app',
        deadlocks: '2',
        idleInTransactionTimeMs: 300,
        recoveryConflicts: '0',
        sessions: '45',
        sessionsAbandoned: '1',
        sessionsFatal: '0',
        sessionsKilled: '0',
        sizeBytes: '1073741824',
        statsResetAt: '2026-07-20T10:00:00.000Z',
        temporaryBytes: '1048576',
        temporaryFiles: '3',
        transactionsCommitted: '12345678901234567890',
        transactionsRolledBack: '5',
      },
    ],
    engine: 'postgresql',
    hostTelemetry: { reason: 'external-provider-required', status: 'unavailable' },
    inRecovery: false,
    longQueryThresholdMs: 30_000,
    sampledAt: '2026-07-20T12:00:00.000Z',
    scope: 'cluster',
    serverStartedAt: '2026-07-18T10:00:00.000Z',
    source: 'postgresql-statistics',
    tracking: { activities: true, counts: true, ioTiming: true },
    ...overrides,
  }
}
